---
AWSTemplateFormatVersion: "2010-09-09"
Description: "Elasticsearch Domain Resource"
Parameters:
    EnvType:
        Type: String
        Description: "Production or Staging?"
        AllowedValues:
        - 'stg'
        - 'prod'
    ElasticsearchDomain:
        Type: String
        Description: "Name of the Elasticsearch Domain"
        MinLength: 3
        MaxLength: 64
        AllowedPattern: "^[a-zA-Z0-9-]*$"
    ElasticsearchManagementIp:
        Type: String
        Description: "(Optional) IP or CIDR to allow for management via https"
        MinLength: 0
        MaxLength: 18
        AllowedPattern: "((\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})(/\\d{1,2})?)?"

Conditions:
    ProdEnv: !Equals [ !Ref EnvType, prod ]
    UseManagementIp: !Not [!Equals [ !Ref ElasticsearchManagementIp, ""]]

Resources:
    ESUser:
        Type: "AWS::IAM::User"
        Properties:
            UserName: !Join ['-', [!Ref ElasticsearchDomain, "user"]]

    ESUserAccessKey:
        Type: "AWS::IAM::AccessKey"
        DependsOn: ESUser
        Properties:
            UserName: !Ref ESUser

    ESDomain:
        Type: "AWS::Elasticsearch::Domain"
        DependsOn: ESUser
        Properties:
            AccessPolicies:
                Version: "2012-10-17"
                Statement:
                    -   Effect: "Allow"
                        Principal:
                            AWS: !GetAtt ESUser.Arn
                        Action: "es:*"
                        Resource: !Join
                            - ''
                            -
                                - 'arn:aws:es:'
                                - !Ref "AWS::Region"
                                - ':'
                                - !Ref "AWS::AccountId"
                                - ':domain/'
                                - !Ref ElasticsearchDomain
                                - '/*'
                    -   !If
                        - UseManagementIp
                        -
                            Effect: "Allow"
                            Principal:
                                AWS: "*"
                            Action: "es:ESHttp*"
                            Resource: !Join
                                - ''
                                -
                                    - 'arn:aws:es:'
                                    - !Ref "AWS::Region"
                                    - ':'
                                    - !Ref "AWS::AccountId"
                                    - ':domain/'
                                    - !Ref ElasticsearchDomain
                                    - '/*'
                            Condition:
                                IpAddress:
                                    "aws:sourceIp":
                                        - !Ref ElasticsearchManagementIp
                        - !Ref "AWS::NoValue"
            AdvancedOptions:
                rest.action.multi.allow_explicit_index: true
            DomainName: !Ref ElasticsearchDomain
            EBSOptions:
                EBSEnabled: true
                VolumeSize: 10
                VolumeType: "gp2"
            ElasticsearchClusterConfig:
                DedicatedMasterEnabled: !If [ProdEnv, true, false]
                DedicatedMasterCount: !If [ProdEnv, 3, !Ref "AWS::NoValue"]
                DedicatedMasterType: !If [ProdEnv, "t2.small.elasticsearch", !Ref "AWS::NoValue"]
                InstanceCount: !If [ProdEnv, 2, 1]
                InstanceType: "t2.small.elasticsearch"
                ZoneAwarenessEnabled: false
            ElasticsearchVersion: "6.0"
            SnapshotOptions:
                AutomatedSnapshotStartHour: 0
            Tags:
                - Key: "Name"
                  Value: !Ref ElasticsearchDomain

Outputs:
    DomainArn:
        Value: !GetAtt ESDomain.DomainArn
    DomainEndpoint:
        Value: !GetAtt ESDomain.DomainEndpoint
    UserAccessKeyID:
        Value: !Ref ESUserAccessKey
    UserSecretAccessKey:
        Value: !GetAtt ESUserAccessKey.SecretAccessKey