---
AWSTemplateFormatVersion: "2010-09-09"
Description: "Do everything, given some parameters."

Parameters:
  CustomAMI:
    Type: String
    Description: Enter the AMI ID for your base image

#  SrcRepo:

  KeyPair:
    Type: String
    Description: Name of the keyPair for access to your system

  ManagementIP:
    Type: String
    Description: "Allows SSH access from this address - CIDR including /32"

# Conditions:

Resources:
  Host:
    DependsOn: HostSecGrp
    Type: "AWS::EC2::Instance"
    Properties:
      InstanceType: t2.nano
      ImageId: !Ref CustomAMI
      KeyName: !Ref KeyPair
      SecurityGroups:
      - !Ref HostSecGrp
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          rm /var/www/html/index.htm*
          echo '<?php echo \'Hello\'; ?>' > /var/www/html/index.php
      Tags:
        - Key: Name
          Value: conduit-instance

  HostSecGrp:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupName: "conduit-stack-secgrp"
      GroupDescription: "SecGrp for conduit-app-instances"
      SecurityGroupIngress:
        - IpProtocol: "tcp"
          FromPort: "80"
          ToPort: "80"
          CidrIp: "0.0.0.0/0"
        - IpProtocol: "tcp"
          FromPort: "22"
          ToPort: "22"
          CidrIp: !Ref ManagementIP

Outputs:
  WebsiteURL:
    Value: !Join
      - ""
      - - "http://"
        - !GetAtt Host.PublicDnsName